name: flutter_expense_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  echart_flutter: ^0.1.0+2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.0-beta.4

flutter:
  uses-material-design: true
