name: flutter_expense_app
description: "A Simple Expense Tracker App"
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  in_app_review: ^2.0.9

  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.0-beta.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/playstore.png
